### ISSUE TITLE
Spacy 3.0 support

### ISSUE THREAD

**Issue by jenojp** [jenojp/extractacy#4]

**Comment by schorndorfer** [comment]
Thanks for the quick update on this! Using it for a project at Northwestern University, as well as negspacy.

**Comment by jenojp** [comment]
cool!!! Setting aside some time this weekend to finish the extractacy refactor. Let me know if you run into any issues with negspacy 1.0.

**Comment by schorndorfer** [comment]
Will do! These 2 packages met two specific needs for my project, kudo to
you for making them available.

**Comment by jenojp** [comment]
spaCy 3.0 support with release v1.0.0

**Comment by schorndorfer** [comment]
Thanks for this! Looking forward to using it.
