### ISSUE TITLE
Extracting attributes from another entity label

### ISSUE THREAD

**Issue by Ibrokhimsadikov** [jenojp/extractacy#5]
I have the following extractacy pattern where I am binding it to label EKG

 ent_result_patterns = {"EKG": {"patterns": [[{"LIKE_NUM": True},]],"n": 4,"direction": "right" },}

However it is extracting  part of another entity:

![image](https://user-images.githubusercontent.com/46495952/107804404-db991580-6d31-11eb-8698-fbe40287ddca.png)

![image](https://user-images.githubusercontent.com/46495952/107804497-efdd1280-6d31-11eb-8e6c-8b01099ec598.png)

This is not correct, is this bug or enhancement

**Comment by jenojp** [comment]
Thanks for posting, let me take a look and recreate

**Comment by jenojp** [comment]
So the behavior of extracting another entity is expected. In some cases we might want to extract another entity such as with dates. You might want to tie the EKG test to its corresponding date. 

What I'd do is add more rules to the expected pattern. For example if you know QTc readings are 3 digits you could do: 
```
ent_result_patterns = {"EKG": {"patterns": [[{"LIKE_NUM": True, "LENGTH": {"==":3}},]],"n": 4,"direction": "right" },}
```
or if they're always followed by a unit of ms, you could do:

```
ent_result_patterns = {"EKG": {"patterns": [[{"LIKE_NUM": True},{"LOWER":"ms"}]],"n": 4,"direction": "right" },}
```

The rules available to you are here: https://spacy.io/usage/rule-based-matching#matcher

**Comment by Ibrokhimsadikov** [comment]
Hi @jenojp  thank you for your post, Yes you are right. I ended up using merge_entities pipe to merge tokens of entity in to one complete token using 
from spacy.pipeline import merge_entites
